package to.etc.pdp11.core.disas;

import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Cross-checks the disassembler against SimH over a 2560-instruction corpus.
 *
 * <p>PLAN.md phase 1 asks for this specifically, and asks for it against SimH rather than
 * against the Pascal: {@code Pdp11DisasU.pas} mirrors SimH's {@code pdp11_sys.c} operand
 * classes by construction, so checking against the authority beats checking against another
 * port of it. The corpus is generated by {@code tools/gen-disas-corpus.sh} and committed, so
 * this test needs no SimH installed.</p>
 *
 * <h2>Why the comparison is normalised rather than literal</h2>
 *
 * <p>SimH and this disassembler agree on what an instruction <i>is</i> and disagree on how to
 * print it: SimH prints minimal-width octal ({@code BR 1002}) where we zero-pad to six digits
 * ({@code br      001002}), separates mnemonic from operands with one space where we pad to a
 * column, prints upper case where we print lower, and prints an unrecognised word as a bare
 * number where we print {@code .WORD nnnnnn}. None of that is a decoding difference, so
 * {@link #normalise} removes all four before comparing.</p>
 */
class DisassemblerSimhCorpusTest {
	/** The address the corpus was generated at; PC-relative decoding depends on it. */
	private static final int BASE = 01000;

	private static final int EXT1 = 0123456;

	private static final int EXT2 = 0154321;

	/**
	 * The two places SimH is known to be wrong, with the word and why. Every entry here is a
	 * claim that <i>we</i> are right, so each one needs a reason that does not reduce to
	 * "the test was failing".
	 */
	private static final Map<Integer, String> SIMH_DISAGREEMENTS = new LinkedHashMap<>();

	static {
		//-- SimH's opcode[] table has the same copy-paste duplicate twice, once in each half of
		//-- the condition-code group: 000256 repeats 000255's text and 000276 repeats 000275's.
		//-- In both words bit 0 is clear, so C is not affected and V is; the documented
		//-- per-flag encoding gives CLN CLZ CLV and SEN SEZ SEV. The Pascal unit header records
		//-- only the first of the pair - the second turned up when this corpus went exhaustive.
		SIMH_DISAGREEMENTS.put(0000256,
			"SimH prints CLN CLZ CLC, duplicating 000255. Bit 0 is clear, so the decode is CLN CLZ CLV.");
		SIMH_DISAGREEMENTS.put(0000276,
			"SimH prints SEN SEZ SEC, duplicating 000275. Bit 0 is clear, so the decode is SEN SEZ SEV.");

		//-- LDEXP is 1764AC+dst: the AC field is bits 7..6, exactly like STEXP at 1750AC+dst.
		//-- SimH decodes STEXP for all four accumulators but LDEXP only for AC0, so its mask
		//-- for this one entry is too wide. macro11 settles it: "LDEXP R0,AC1" assembles to
		//-- 176500, so 176500 is a valid instruction and SimH's refusal to decode it is wrong.
		for(int ac = 1; ac <= 3; ac++) {
			for(int dst = 0; dst < 64; dst++) {
				SIMH_DISAGREEMENTS.put(0176400 | (ac << 6) | dst,
					"SimH decodes LDEXP for AC0 only; macro11 assembles LDEXP R0,AC" + ac
						+ " to 0" + Integer.toOctalString(0176400 | (ac << 6)) + ", so AC1..AC3 are legal.");
			}
		}
	}

	@Test
	void matchesSimhOverTheWholeCorpus() throws IOException {
		List<String> mismatches = new ArrayList<>();
		int compared = 0;
		int excused = 0;

		for(CorpusEntry entry : loadCorpus()) {
			MemoryImage mem = MemoryImage.ofWords(BASE, entry.word, EXT1, EXT2);
			DecodedInstruction di = Disassembler.disassemble(mem, BASE);

			String ours = normalise(di.text());
			String theirs = normalise(entry.simhText);

			if(ours.equals(theirs)) {
				compared++;
				continue;
			}
			String reason = SIMH_DISAGREEMENTS.get(entry.word);
			if(reason != null) {
				excused++;
				continue;
			}
			mismatches.add(String.format("%06o: simh %-28s ours %s", entry.word, theirs, ours));
		}

		if(!mismatches.isEmpty()) {
			fail(mismatches.size() + " of " + (compared + mismatches.size() + excused)
				+ " instructions disagree with SimH:\n  " + String.join("\n  ", mismatches));
		}
		assertTrue(compared > 2000, "the corpus should be substantial, only compared " + compared);
		assertTrue(excused > 0, "the documented SimH disagreements should still be reachable in the corpus");
	}

	/**
	 * Reduce a disassembly to what it decodes to, discarding how it is spelled: case,
	 * mnemonic padding, octal zero-padding, and SimH's habit of printing an unrecognised word
	 * as a bare number.
	 */
	private static String normalise(String text) {
		String s = text.trim().toLowerCase().replaceAll("\\s+", " ");

		//-- SimH spells the FP11 accumulators F0..F5; DEC's handbook, MACRO-11 and the rest of
		//-- PDP11GUI spell them AC0..AC5. Same register, different house style.
		s = s.replaceAll("\\bf([0-5])\\b", "ac$1");

		//-- SimH prints an unknown opcode as just its value; we print ".WORD nnnnnn".
		if(s.matches("[0-7]+"))
			s = ".word " + s;

		//-- Strip leading zeros from every octal run, leaving at least one digit.
		Matcher m = Pattern.compile("[0-7]+").matcher(s);
		StringBuilder sb = new StringBuilder();
		while(m.find()) {
			String digits = m.group().replaceFirst("^0+(?=.)", "");
			m.appendReplacement(sb, digits);
		}
		m.appendTail(sb);
		return sb.toString();
	}

	private record CorpusEntry(int word, String simhText) {
	}

	private static List<CorpusEntry> loadCorpus() throws IOException {
		List<CorpusEntry> list = new ArrayList<>();
		try(InputStream is = DisassemblerSimhCorpusTest.class.getResourceAsStream("/disas/simh-corpus.txt")) {
			if(is == null)
				throw new IllegalStateException("/disas/simh-corpus.txt is missing; regenerate it with tools/gen-disas-corpus.sh");
			BufferedReader br = new BufferedReader(new InputStreamReader(is, StandardCharsets.US_ASCII));
			String line;
			while(null != (line = br.readLine())) {
				if(line.isBlank() || line.startsWith("#"))
					continue;
				int tab = line.indexOf('\t');
				if(tab < 0)
					throw new IllegalStateException("Malformed corpus line: " + line);
				list.add(new CorpusEntry(Integer.parseInt(line.substring(0, tab).trim(), 8),
					line.substring(tab + 1)));
			}
		}
		return list;
	}
}
