#!/bin/bash
#
# Generates the disassembler cross-check corpus from SimH.
#
# PLAN.md phase 1 says to validate the disassembler against SimH itself rather than against
# the Pascal port, because Pdp11DisasU.pas explicitly mirrors SimH's pdp11_sys.c operand
# classes -- checking against the authority beats checking against another port of it. This
# script is that check, run once; the result is committed so the test needs no SimH.
#
# Output format, one instruction per line, tab-separated:
#     <word>[,<ext1>[,<ext2>]]<TAB><simh text>
# with all numbers in octal. Lines starting with '#' are comments.
#
# Usage: tools/gen-disas-corpus.sh > pdp11-core/src/test/resources/disas/simh-corpus.txt
#
set -euo pipefail

SIMH=${SIMH:-$(command -v pdp11 || true)}
if [ -z "$SIMH" ]; then
	echo "SimH's pdp11 is not on PATH; set SIMH=/path/to/pdp11" >&2
	exit 1
fi

# The pdp11 build at /home/jal/bin was linked against libvdeplug.so.2 (VDE networking) and
# will not start without it; the library is not installed and Ubuntu now ships it as
# libvdeplug2t64. It is only needed to satisfy the loader -- nothing here goes near the
# network -- so unpacking the .deb somewhere and pointing LD_LIBRARY_PATH at it is enough:
#
#     apt-get download libvdeplug2t64 && dpkg-deb -x libvdeplug2t64_*.deb /tmp/vde
#     export LD_LIBRARY_PATH=/tmp/vde/usr/lib/x86_64-linux-gnu
#
# Phase 4's SimH integration tests will hit the same wall.
if ! echo quit | "$SIMH" >/dev/null 2>&1; then
	echo "$SIMH will not start. If it is missing libvdeplug.so.2, see the comment above." >&2
	"$SIMH" </dev/null 2>&1 | head -2 >&2 || true
	exit 1
fi

# Instructions are deposited at 1000 and disassembled there. The address matters: PC-relative
# operands and branch targets are computed from it, so the expected text is only meaningful
# together with it.
BASE=1000

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# --- The words to test ---------------------------------------------------------------------
# All of them. Every 16-bit value is a word some PDP-11 memory location could hold, and the
# Disassembler window will be pointed at exactly such memory, so "we checked a representative
# sample" is a weaker claim than this file needs to support. 65536 words costs about five
# minutes to generate and is run once.
seq 0 65535 | while read -r n; do printf '%o\n' "$n"; done > "$work/words"

# --- Ask SimH ------------------------------------------------------------------------------
{
	echo "set cpu 11/70"
	echo "set cpu 256k"
	# Two extension words follow every instruction so that any addressing mode needing one
	# finds valid, recognisable memory. 123456/154321 are arbitrary but distinctive. They are
	# deposited once: nothing below ever writes above $BASE, so they stay put, and hoisting
	# them out of the loop halves the number of commands SimH has to parse.
	echo "deposit $(( BASE + 2 )) 123456"
	echo "deposit $(( BASE + 4 )) 154321"
	while read -r w; do
		echo "deposit $BASE $w"
		echo "examine -m $BASE"
	done < "$work/words"
	echo "quit"
} > "$work/cmd.simh"

echo "# PDP-11 disassembly corpus, generated by tools/gen-disas-corpus.sh"
echo "# Oracle: $(echo quit | "$SIMH" 2>/dev/null | grep -m1 simulator | sed 's/^ *//')"
echo "# Every 16-bit word, at octal $BASE, followed by extension words 123456 and 154321."
echo "# Format: word<TAB>simh-text     (octal; compared after normalisation, see DisassemblerSimhCorpusTest)"

"$SIMH" "$work/cmd.simh" 2>/dev/null \
	| sed -n 's/^0*'"$BASE"':\t\(.*\)$/\1/p' > "$work/texts"

paste "$work/words" "$work/texts"
